version: "3.8"
services:
  eureka-server:
    build:
      context: ./Eureka-server/
      dockerfile: Dockerfile
    restart: always
    container_name: eureka-container
    image: eureka-image
    ports:
      - "8761:8761"
    networks:
      - bored-network

  userDB:
    container_name: userDB-container
    image: mongo
    restart: always
    networks:
      - bored-network
    volumes:
      - userVolume:/data/db
    ports:
      - "27017:27017"

  baladeDB:
    container_name: baladeDB-container
    image: mongo
    restart: always
    networks:
      - bored-network
    volumes:
      - baladeVolume:/data/db
    ports:
      - "27018:27017"


  balade-service:
    build:
      context: ./reservevelo-micro-balade
      dockerfile: Dockerfile
    container_name: balade-container
    image: balade-image
    networks:
      - bored-network
    depends_on:
      - eureka-server
      - baladeDB
    restart: always
    ports:
      - "8096:8096"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - eureka.instance.preferIpAddress=true
      - eureka.instance.leaseRenewalIntervalInSeconds=10
      - eureka.instance.leaseExpirationDurationInSeconds=30
      - spring.data.mongodb.uri=mongodb://baladeDB:27017/baladeDatabase
      - spring.data.mongodb.database=baladeDatabase

  user-service:
    build:
      context: ./reservevelo-micro-user
      dockerfile: Dockerfile
    container_name: user-container
    image: user-image
    networks:
      - bored-network
    depends_on:
      - eureka-server
      - userDB
    restart: always
    ports:
      - "8097:8097"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - eureka.instance.preferIpAddress=true
      - eureka.instance.leaseRenewalIntervalInSeconds=10
      - eureka.instance.leaseExpirationDurationInSeconds=30
      - spring.data.mongodb.uri=mongodb://userDB:27017/userDatabase
      - spring.data.mongodb.database=userDatabase

  api-gateway:
    build:
      context: ./cloud-gateway-api
      dockerfile: Dockerfile
    container_name: api-gateway-container
    image: api-gateway-image
    restart: always
    networks:
      - bored-network
    depends_on:
      - eureka-server
      - user-service
      - balade-service
    ports:
      - "8051:8051"
    environment:
      eureka.client.service-url.defaultZone : http://eureka-server:8761/eureka
      EUREKA_INSTANCE_PREFERIPADDRESS : true
      EUREKA_INSTANCE_LEASERENEWALINTERVALINSECONDS: 10
      EUREKA_INSTANCE_LEASEEXPIRATIONDURATIONINSECONDS: 30
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: user-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://user-service:8097
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/api/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: balade-service
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://balade-service:8096
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/balade/**

      



networks:
  bored-network:
    name: bored-network
volumes:
  userVolume:
  baladeVolume:

  
  
